# Depencencias de desarrollo
FROM node:19.2-alpine3.16 as deps
# /app

# cd app
WORKDIR /app

# Dest /app
COPY package.json ./

# Instalar las dependencias
RUN npm install

# ----------------------------------------------------------------------------------

# Build y test
FROM node:19.2-alpine3.16 as builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules

COPY . .

RUN npm run test

# ----------------------------------------------------------------------------------

# Dependencias de producción
FROM node:19.2-alpine3.16 as prod-deps

WORKDIR /app

COPY package.json ./

RUN npm install --prod

# ----------------------------------------------------------------------------------

# Ejecutar la APP
FROM node:19.2-alpine3.16 as runner

WORKDIR /app

COPY --from=prod-deps /app/node_modules ./node_modules

COPY app.js ./

COPY tasks/ ./tasks

CMD ["node", "app.js"]

